name: rag-application

services:
  web:
    build:
      context: web/
      dockerfile: web.Dockerfile
    ports:
      - "80:80"
    env_file:
      - web/.env
    volumes:
      - ./persistent_data/web:/home/appuser/data
    # depends_on:
    #   backend_entrypoint:
    #     condition: service_healthy

  
  backend_entrypoint:
    build:
      context: backend_entrypoint/
      dockerfile: backend_entrypoint.Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - backend_entrypoint/.env
    volumes:
      - ./persistent_data/backend_entrypoint:/home/appuser/data
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://$$HOST:$$PORT/ping"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5