---
name: rag-application

services:
  web:
    build:
      context: web/
      dockerfile: web.dev.Dockerfile
    ports:
      - 80:80
    env_file:
      - web/.env
    volumes:
      - ./persistent_data/web:/home/appuser/data
      - ./web:/home/appuser/app
    depends_on:
      - backend_entrypoint

  backend_entrypoint:
    build:
      context: backend_entrypoint/
      dockerfile: backend_entrypoint.dev.Dockerfile
    ports:
      - 8080:8080
    env_file:
      - backend_entrypoint/.env
    volumes:
      - ./persistent_data/backend_entrypoint:/home/appuser/data
      - ./backend_entrypoint:/home/appuser/app

