[project]
name = "rag_application"
version = "0.1.0"
requires-python=">=3.12"
dependencies = [
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "mypy",
    "pre-commit",
    "pylint",
    "requests==2.32.3",
    "uvicorn==0.34.3",
    "fastapi==0.115.12",
    "gradio==5.33.0"

]
